su:
  - igarashi
  - saito
  - ina
  - t-sekiym

year:   2010

build:
  command:
    - ocamlbuild -I src main.native -no-hygiene && ocamlbuild -clean
    - ocamlbuild -I src test.native -no-hygiene
  file_location:
    report2:
      - location: report2
    report3:
      - exercise:
          - Ex.4.8
          - Ex.4.9
        location: report3-89
      - exercise:
          - Ex.4.9
        location: report3-9
      - exercise:
          - Ex.4.8
        location: report3-8
      - location: report3

test:
  sandbox: "http://sandbox.sato.kuis.kyoto-u.ac.jp/isle4fp/tester.cgi"
