su:
  - igarashi
  - saito
  - ina
  - t-sekiym

record:
  show_login: false
  open: false
  detail: false

build:
  command:
    - ocamlbuild -I src main.byte -no-hygiene && ocamlbuild -clean
    - ocamlbuild -I src test.byte -no-hygiene
  file_location:
    report2:
      - exercise:
          - Ex.3.16
        location: report2-16
      - exercise:
          - Ex.3.8
        location: report2
      - location: report2-4
    report3:
      - exercise:
          - Ex.4.8
          - Ex.4.9
        location: report3-89
      - exercise:
          - Ex.4.9
        location: report3-9
      - exercise:
          - Ex.4.8
        location: report3-8
      - exercise:
          - Ex.4.6
        location: report3
      - location: report3-1

test:
  files:
    - test.byte
    - solved.in
  run: test.byte
  input: solved.in
  output: :argument
  sandbox: "http://sandbox.sato.kuis.kyoto-u.ac.jp/isle4fp/tester.cgi"
