su:
  - igarashi
  - saito
  - ina
  - t-sekiym

record:
  show_login: false
  open: false
  detail: false

check:
  default:
    build:
      command:
        - ocamlbuild -I src main.byte -no-hygiene && ocamlbuild -clean
        - ocamlbuild -I src test.byte -no-hygiene
    test:
      files:
        - test.byte
        - solved.in
      run: test.byte
      input: solved.in
      output: :argument
      sandbox: "http://sandbox.sato.kuis.kyoto-u.ac.jp/isle4fp/tester.cgi"
  report1:
    build:
      command:
        - ./ocamlc_all
      file_location:
        - location: report1
    test:
      run: # nothing
  report2:
    build:
      file_location:
        - exercise:
            - Ex.3.16
          location: report2-16
        - exercise:
            - Ex.3.8
          location: report2
        - location: report2-4
  report3:
    build:
      file_location:
        - exercise:
            - Ex.4.8
            - Ex.4.9
          location: report3-89
        - exercise:
            - Ex.4.9
          location: report3-9
        - exercise:
            - Ex.4.8
          location: report3-8
        - exercise:
            - Ex.4.6
          location: report3
        - location: report3-1
