scheme:
  - id: report1
    type: post
    name: "課題1: Objective Caml演習"
    record:
      - field: name
        label: "名前"
      - field: status
        label: "課題1"
        class: status
      - field: unsolved
        label: "未解答の必修問題"
        class: unsolved
      - field: optional
        label: "オプション問題の解答数"
  - id: report2
    type: post
    update: auto
    name: "課題2: インタプリタ作成実験"
    record:
      - field: name
        label: "名前"
      - field: status
        label: "課題2"
        class: status
      - field: unsolved
        label: "未解答の必修問題"
        class: unsolved
      - field: optional1
        label: "★問題の解答数"
      - field: optional2
        label: "★★問題の解答数"
      - field: optional3
        label: "★★★問題の解答数"
  - id: report3
    type: post
    update: auto
    name: "課題3: 型検査・推論器作成実験"
    record:
      - field: name
        label: "名前"
      - field: status
        label: "課題3"
        class: status
      - field: unsolved
        label: "未解答の必修問題"
        class: unsolved
      - field: optional1
        label: "★問題の解答数"
      - field: optional2
        label: "★★問題の解答数"
      - field: optional3
        label: "★★★問題の解答数"

regex: "^Ex((?:\\.\\d+)+)"

report:
  report1:
    Ex.2.1:
    Ex.2.1(1):
    Ex.2.1(2):
    Ex.2.1(3):
    Ex.2.1(4):
    Ex.2.1(5):
    Ex.2.1(6):
    Ex.2.2:
    Ex.2.2(1):
    Ex.2.2(2):
    Ex.2.2(3):
    Ex.2.2(4):
    Ex.2.3:
    Ex.2.3(1):
    Ex.2.3(2):
    Ex.2.3(3):
    Ex.2.3(4):
    Ex.2.4:
    Ex.2.5:
    Ex.2.6:
    Ex.2.6(1):
    Ex.2.6(2):  { required: 1 }
    Ex.2.6(3):
    Ex.2.6(4):  { required: 1 }
    Ex.3.1:
    Ex.3.1(1):
    Ex.3.1(2):
    Ex.3.1(3):
    Ex.3.2:
    Ex.3.3:
    Ex.3.4:
    Ex.3.5:
    Ex.3.6:
    Ex.3.7:
    Ex.3.7(1):  { required: 1 }
    Ex.3.7(2):  { required: 1 }
    Ex.3.8:
    Ex.3.9:
    Ex.3.10:
    Ex.3.11:
    Ex.3.11(1): { required: 1 }
    Ex.3.11(2): { required: 1 }
    Ex.3.11(3): { required: 1 }
    Ex.3.11(4): { required: 1 }
    Ex.3.12:
    Ex.4.1:     { required: 1 }
    Ex.4.2:
    Ex.4.3:
    Ex.4.4:     { required: 1 }
    Ex.4.5:     { required: 1 }
    Ex.4.6:
    Ex.4.7:     { required: 1 }
    Ex.4.8:
    Ex.5.1:
    Ex.5.2:
    Ex.5.3:     { required: 4 }
    Ex.5.3(1):
    Ex.5.3(2):
    Ex.5.3(3):
    Ex.5.3(4):
    Ex.5.3(5):
    Ex.5.3(6):
    Ex.5.4:
    Ex.5.5:
    Ex.5.6:     { required: 1 }
    Ex.5.7:
    Ex.5.8:
    Ex.6.1:
    Ex.6.2:     { required: 1 }
    Ex.6.3:
    Ex.6.4:
    Ex.6.5:
    Ex.6.6:     { required: 1 }
    Ex.6.7:
    Ex.6.8:
    Ex.6.9:     { required: 1 }
    Ex.6.10:    { required: 2 }
    Ex.6.10(1):
    Ex.6.10(2):
    Ex.6.10(3):
    Ex.6.10(4):
    Ex.6.10(5):
    Ex.7.1:
    Ex.7.2:     { required: 1 }
    Ex.7.3:
    Ex.7.4:     { required: 1 }
    Ex.7.5:
    Ex.7.6:     { required: 1 }
    Ex.7.7:
    Ex.7.8:     { required: 1 }
    Ex.7.9:
    Ex.7.10:
  report2:
    Ex.3.1:     { required: 1 }
    Ex.3.2:     { level: 2 }
    Ex.3.3:     { level: 1 }
    Ex.3.4:     { required: 1 }
    Ex.3.5:     { level: 2 }
    Ex.3.6:     { level: 2 }
    Ex.3.7:     { level: 2 }
    Ex.3.8:     { required: 1 }
    Ex.3.9:     { level: 2 }
    Ex.3.10:    { level: 1 }
    Ex.3.11:    { level: 1 }
    Ex.3.12:    { level: 1 }
    Ex.3.13:    { level: 1 }
    Ex.3.14:    { required: 1 }
    Ex.3.15:    { level: 2 }
    Ex.3.16:    { level: 2 }
    Ex.3.17:    { level: 1 }
    Ex.3.18:    { level: 1 }
    Ex.3.19:    { level: 3 }
    Ex.3.20:    { level: 2 }
  report3:
    Ex.4.1:     { required: 1 }
    Ex.4.2:     { required: 1 }
    Ex.4.3:     { required: 1 }
    Ex.4.4:     { required: 1 }
    Ex.4.5:     { required: 1 }
    Ex.4.6:     { required: 1 }
    Ex.4.7:     { level: 2 }
    Ex.4.8:     { level: 2 }
    Ex.4.9:     { level: 2 }
    Ex.4.10:    { level: 1 }
    Ex.4.11:    { level: 3 }
    Ex.4.12:    { level: 3 }
