scheme:
  - id: example_report
    type: post
    update: auto
    name: "Report1"
    record:
      - field: name
        label: "Name"
      - field: status
        label: "Report"
      - field: unsolved
        label: "Unsolved"

report:
  example_report:
    Ex.1.1: { required: 1 }
    Ex.1.2: { required: 0 }
    Ex.1.3: { level: 1 }
    Ex.1.4: { priority: 1 } # Empty priority is the same as 0
